-- Add migration script here
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_job_id TEXT NOT NULL,
    is_running BOOLEAN NOT NULL DEFAULT 'f',
    retries BIGINT NOT NULL DEFAULT 0,
    run_after TIMESTAMP WITH TIME ZONE NOT NULL,
    job_data BYTEA NOT NULL
);
CREATE INDEX jobs_running ON jobs (is_running);
CREATE INDEX jobs_run_after ON jobs (run_after);
CREATE UNIQUE INDEX jobs_unique_id ON jobs(unique_job_id);
